services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: postgres
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - nest-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nest-network

volumes:
  postgres:
    name: nest-db

networks:
  nest-network:
    driver: bridge
