default:
  type: postgres
  host: localhost
  port: 5432
  username: test
  password: test
  database: starter
  synchronize: true
  logging: true
  entities:
    - dist/**/*.entity.js
  migrations:
    - dist/database/migrations/**/*.js
  subscribers:
    - dist/database/subscriber/**/.js
  cli:
    entitiesDir: src
    migrationsDir: database/migrations
    subscribersDir: database/subscriber
